version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blog_db
    volumes:
      - data:/var/lib/postgresql/data

  mailhog:
    container_name: maildev
    image: maildev/maildev
    ports:
      - 1025:1025
      - 1080:1080
    
volumes:
  data: {}