version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blogify
    volumes:
      - pg_data:/var/lib/postgresql/data

  mailhog:
    container_name: maildev
    image: maildev/maildev
    ports:
      - 1025:1025
      - 1080:1080

  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/blogify;
      /usr/bin/mc policy set public myminio/blogify read-only user=*;
      exit 0;
      "
    
volumes:
  pg_data: {}
  minio_data: {}
