spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABSE_URL:jdbc:postgresql://localhost:5432/blogify}
    username: ${DATABSE_USERNAME:postgres}
    password: ${DATABSE_PASSWORD:password}
  flyway:
    user: ${DATABSE_USERNAME:postgres}
    password: ${DATABSE_PASSWORD:password}
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:mialdev@spring.in}
    protocol: smtp
  security:
    secret-key: ${SECRET_KEY}
    expiration: 60000
  
minio:
  access-key: minioadmin
  secret-key: minioadmin
  end-point: http://localhost:9000
  bucket: blogify
