spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blog_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
  mail:
    host: localhost
    port: 1025
    username: springboot@blogapi.com
    protocol: smtp

springdoc:
  swagger-ui:
    path: /docs
    
security:
  jwt:
    secret-key: 815F1298534CA2989B84C1C2F48D4609E7A05811E0700653661466A6
    expiration: 60000

