spring:
  application:
    name: blog-api
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
  
springdoc:
  swagger-ui:
    path: /docs
  
server:
  port: 8080
  