spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blog_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
  mail:
    host: localhost
    port: 1025
    protocol: smtp
    
jwt:
  secret-key: 815F1298534CA2989B84C1C2F48D4609E7A05811E0700653661466A6
  expiration-time: 60